Proyecto.UI/Controllers/ActividadesPersonaController.cs
using System;
using System.Web.Mvc;
using Proyecto.Abstracciones.LogicaDeNegocio.ActividadesPersona;
using Proyecto.AccesoADatos.ActividadesPersona;
using Proyecto.LogicaDeNegocio.ActividadesPersona;

namespace Proyecto.UI.Controllers
{
    public class ActividadesPersonaController : Controller
    {
        private readonly IObtenerActividadesPersonaLN _obtenerLN;
        private readonly IRegistrarActividadPersonaLN _registrarLN;
        private readonly IEliminarActividadPersonaLN _eliminarLN;

        public ActividadesPersonaController()
        {
            var ad = new ActividadesPersonaAD();
            _obtenerLN = new ObtenerActividadesPersona(ad);
            _registrarLN = new RegistrarActividadPersona(ad);
            _eliminarLN = new EliminarActividadPersona(ad);
        }

        // GET: /ActividadesPersona/Ver/5
        public ActionResult Ver(int idPersona)
        {
            try
            {
                var vm = _obtenerLN.Ejecutar(idPersona);
                ViewBag.Persona = vm.Persona;
                ViewBag.ActividadesDisponibles = vm.Disponibles;
                return View(vm.Lista);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("ListaDePersonas", "Personas");
            }
        }

        [HttpPost]
        public ActionResult Agregar(int idPersona, int idActividad)
        {
            _registrarLN.Ejecutar(idPersona, idActividad);
            return RedirectToAction("Ver", new { idPersona });
        }

        [HttpPost]
        public ActionResult Eliminar(int idActividadPersona, int idPersona)
        {
            _eliminarLN.Ejecutar(idActividadPersona);
            return RedirectToAction("Ver", new { idPersona });
        }
    }
}

Proyecto.UI/Views/Personas/Create.cshtml
@model Proyecto.Abstracciones.Entidades.Persona

@{
    ViewBag.Title = "CrearPersona";
}

<h2>CrearPersona</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Persona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdPersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdentificacionPersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdentificacionPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdentificacionPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoIdentificacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoIdentificacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoIdentificacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombrePersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombrePersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombrePersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrimerApellidoPersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrimerApellidoPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrimerApellidoPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SegundoApellidoPersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SegundoApellidoPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SegundoApellidoPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CorreoElectronico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CorreoElectronico, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CorreoElectronico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstadoDeRiesgo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadoDeRiesgo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadoDeRiesgo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaDeRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaDeRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaDeRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaDeModificacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaDeModificacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaDeModificacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto.UI/Views/Personas/Delete.cshtml
@model Proyecto.Abstracciones.Entidades.Persona

@{
    ViewBag.Title = "EliminarPersona";
}

<h2>EliminarPersona</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdPersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdPersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdentificacionPersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdentificacionPersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoIdentificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoIdentificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombrePersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombrePersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrimerApellidoPersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrimerApellidoPersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SegundoApellidoPersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SegundoApellidoPersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CorreoElectronico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoDeRiesgo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoDeRiesgo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDeRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDeRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDeModificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDeModificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Proyecto.UI/Views/Personas/Details.cshtml
@model Proyecto.Abstracciones.Entidades.Persona

@{
    ViewBag.Title = "DetallesPersona";
}

<h2>DetallesPersona</h2>

<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdPersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdPersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdentificacionPersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdentificacionPersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoIdentificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoIdentificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombrePersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombrePersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrimerApellidoPersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrimerApellidoPersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SegundoApellidoPersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SegundoApellidoPersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CorreoElectronico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoDeRiesgo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoDeRiesgo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDeRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDeRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDeModificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDeModificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdPersona }, new { @class = "btn btn-warning" })
    @Html.ActionLink("Volver a la lista", "ListaDePersonas", null, new { @class = "btn btn-secondary" })
</p>

Proyecto.UI/Views/Personas/Edit.cshtml
@model Proyecto.Abstracciones.Entidades.Persona

@{
    ViewBag.Title = "EditarPersona";
}

<h2>EditarPersona</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Persona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdPersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdentificacionPersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdentificacionPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdentificacionPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoIdentificacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoIdentificacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoIdentificacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombrePersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombrePersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombrePersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrimerApellidoPersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrimerApellidoPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrimerApellidoPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SegundoApellidoPersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SegundoApellidoPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SegundoApellidoPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CorreoElectronico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CorreoElectronico, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CorreoElectronico, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstadoDeRiesgo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadoDeRiesgo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadoDeRiesgo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaDeRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaDeRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaDeRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaDeModificacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaDeModificacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaDeModificacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto.UI/Views/Personas/ListaDePersonas.cshtml
@model IEnumerable<Proyecto.Abstracciones.Entidades.Persona>

@{
    ViewBag.Title = "ListaDePersonas";
}

<h2>ListaDePersonas</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-striped align-middle">
    <thead class="table-dark">
        <tr class="text-center">
            <th>Identificación</th>
            <th>Tipo</th>
            <th>Nombre</th>
            <th>Teléfono</th>
            <th>Correo</th>
            <th>Estado</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.IdentificacionPersona</td>
                <td>@(item.TipoIdentificacion == 1 ? "Física" : "Jurídica")</td>
                <td>@item.NombrePersona</td>
                <td>@item.Telefono</td>
                <td>@item.CorreoElectronico</td>
                <td>@(item.Estado ? "Activo" : "Inactivo")</td>
                <td class="text-center">
                    @Html.ActionLink("Detalles", "Details", new { id = item.IdPersona }, new { @class = "btn btn-info btn-sm me-1" })
                    @Html.ActionLink("Editar", "Edit", new { id = item.IdPersona }, new { @class = "btn btn-warning btn-sm me-1" })
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.IdPersona }, new { @class = "btn btn-danger btn-sm" })
                    <a href="@Url.Action("Ver","ActividadesPersona", new { idPersona = item.IdPersona })"
                       class="btn btn-primary btn-sm">Ver Actividades</a>

                </td>
            </tr>
        }
    </tbody>
</table>